FROM python:3.10-slim

WORKDIR /app

# Copiar dependencias de Python
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

# Exponer el puerto del API de Flask
EXPOSE 3000

# Comando para ejecutar la aplicación Flask
CMD ["python", "app.py"]
