events {}

http {
    server {
        listen 80;

        location /api/payment/checkout {
            proxy_pass http://payment-service:3000/checkout;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/unlock {
            proxy_pass http://unlock-service:3000/unlock;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/telemetry {
            proxy_pass http://telemetry-service:3000/telemetry;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/identity/verify {
            proxy_pass http://identity-service:3000/verify;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 404 'API Gateway: ruta no encontrada';
        }
    }
}
